### ISSUE TITLE
plotting 

### ISSUE THREAD

**Issue by mattben** [CDAT/cdatweb#110]
James,
- make the plot type draggable
- make the plot canvases droppable
- once you click a variable it should show up in the variable box (subsetting)
- once a plot type, and variable are dropped on a canvas it should generate and display the plot.

**Comment by James-Crean** [comment]
Under my fork I have created a branch "variable-drag-and-drop". Multiple variables can be selected across ACME and ESGF tabs at once and added to the current variable pool. Dragging and dropping onto individual windows works, and plotting "technically" works. 

There does however seem to be an issue with getting variables through esgf. Both the master version and CDATWEB2.0 on my local machine are not able to plot those variables due to the error: 

`Error in DODS open of: {url_here}`

I am guessing that it has to do with authentication not being done before attempting to open the url. 
http://test.opendap.org/opendap/data/nc/coads_climatology.nc with variable 'SST' as per the example plot works.

**Comment by doutriaux1** [comment]
@James-Crean try to remove your ${HOME}/.dodsrc then  rerun the esgf authentification (I usually run one of their wget scripts to get the credentials).
That might help.

**Comment by mattben** [comment]
Dead Project
